<?php

/*
 * Cypher DSL
 * Copyright (C) 2021  Wikibase Solutions
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

namespace WikibaseSolutions\CypherDSL\Traits;

/**
 * Used for automatically generating names.
 *
 * @internal This trait is not covered by the backwards compatibility guarantee of php-cypher-dsl
 */
trait NameGenerationTrait
{
    /**
     * Generates a unique random identifier.
     *
     * It is not entirely guaranteed that this function gives a truly unique string. However, because the
     * number of possible strings is so huge, it should not be a problem. The returned string will consist of
     * $length (default: 32) hexadecimal digits, prepended with $prefix. Since the prefix is predetermined, it does
     * not count towards the entropy of the returned string. Therefore, given the default length of 32, the change
     * of any two strings generated by this function being the same is 1 / 16^32, or about 1 / 3.4 * 10^38.
     *
     * @note The returned string is not cryptographically secure.
     *
     * @param string $prefix The prefix to put before the name. Must start with a letter to adhere to cypher namings.
     * @param int|null $length The length of the generated name in bytes.
     *
     * @return string
     */
    private function generateIdentifier(string $prefix = 'var', int $length = 32): string
    {
        $random = '';
        for ($i = 0; $i < $length; ++$i) {
            $random .= dechex(mt_rand(0, 15));
        }

        return $prefix . $random;
    }
}
